require: rubocop-performance

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**/*'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/LineLength:
  Max: 90
  Exclude:
    - 'Gemfile'
    - 'db/seeds.rb'

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  CountComments: false
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

StabbyLambdaParentheses:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty
